[package]
name = "tellur_core"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
assert_matches.workspace = true
criterion.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true

[[bench]]
name = "benchmark"
harness = false
